// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: BoardGamesGrpc/protos/user.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace BoardGamesGrpc.Users {
  public static partial class UserService
  {
    static readonly string __ServiceName = "BoardGamesGrpc.Users.UserService";

    static readonly grpc::Marshaller<global::BoardGamesGrpc.Users.LoginRequest> __Marshaller_BoardGamesGrpc_Users_LoginRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BoardGamesGrpc.Users.LoginRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::BoardGamesGrpc.Users.UserResponse> __Marshaller_BoardGamesGrpc_Users_UserResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BoardGamesGrpc.Users.UserResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::BoardGamesGrpc.Users.RegistrationRequest> __Marshaller_BoardGamesGrpc_Users_RegistrationRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BoardGamesGrpc.Users.RegistrationRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::BoardGamesGrpc.Users.ServiceResponse> __Marshaller_BoardGamesGrpc_Users_ServiceResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::BoardGamesGrpc.Users.ServiceResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::BoardGamesGrpc.Users.LoginRequest, global::BoardGamesGrpc.Users.UserResponse> __Method_Login = new grpc::Method<global::BoardGamesGrpc.Users.LoginRequest, global::BoardGamesGrpc.Users.UserResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Login",
        __Marshaller_BoardGamesGrpc_Users_LoginRequest,
        __Marshaller_BoardGamesGrpc_Users_UserResponse);

    static readonly grpc::Method<global::BoardGamesGrpc.Users.RegistrationRequest, global::BoardGamesGrpc.Users.ServiceResponse> __Method_Registration = new grpc::Method<global::BoardGamesGrpc.Users.RegistrationRequest, global::BoardGamesGrpc.Users.ServiceResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Registration",
        __Marshaller_BoardGamesGrpc_Users_RegistrationRequest,
        __Marshaller_BoardGamesGrpc_Users_ServiceResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::BoardGamesGrpc.Users.UserReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UserService</summary>
    [grpc::BindServiceMethod(typeof(UserService), "BindService")]
    public abstract partial class UserServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::BoardGamesGrpc.Users.UserResponse> Login(global::BoardGamesGrpc.Users.LoginRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::BoardGamesGrpc.Users.ServiceResponse> Registration(global::BoardGamesGrpc.Users.RegistrationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UserService</summary>
    public partial class UserServiceClient : grpc::ClientBase<UserServiceClient>
    {
      /// <summary>Creates a new client for UserService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UserServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UserService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UserServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UserServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UserServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::BoardGamesGrpc.Users.UserResponse Login(global::BoardGamesGrpc.Users.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Login(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::BoardGamesGrpc.Users.UserResponse Login(global::BoardGamesGrpc.Users.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Login, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::BoardGamesGrpc.Users.UserResponse> LoginAsync(global::BoardGamesGrpc.Users.LoginRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LoginAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::BoardGamesGrpc.Users.UserResponse> LoginAsync(global::BoardGamesGrpc.Users.LoginRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Login, null, options, request);
      }
      public virtual global::BoardGamesGrpc.Users.ServiceResponse Registration(global::BoardGamesGrpc.Users.RegistrationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Registration(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::BoardGamesGrpc.Users.ServiceResponse Registration(global::BoardGamesGrpc.Users.RegistrationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Registration, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::BoardGamesGrpc.Users.ServiceResponse> RegistrationAsync(global::BoardGamesGrpc.Users.RegistrationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegistrationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::BoardGamesGrpc.Users.ServiceResponse> RegistrationAsync(global::BoardGamesGrpc.Users.RegistrationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Registration, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UserServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UserServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UserServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Login, serviceImpl.Login)
          .AddMethod(__Method_Registration, serviceImpl.Registration).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UserServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Login, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::BoardGamesGrpc.Users.LoginRequest, global::BoardGamesGrpc.Users.UserResponse>(serviceImpl.Login));
      serviceBinder.AddMethod(__Method_Registration, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::BoardGamesGrpc.Users.RegistrationRequest, global::BoardGamesGrpc.Users.ServiceResponse>(serviceImpl.Registration));
    }

  }
}
#endregion
