//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoardGameDatabase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoardGameDatabase.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie poprawne dane. Nie można się zalogować.
        /// </summary>
        internal static string CantLogin {
            get {
                return ResourceManager.GetString("CantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podany Email istnieje już w bazie danych.
        /// </summary>
        internal static string EmailDuplicate {
            get {
                return ResourceManager.GetString("EmailDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie poprawny adres Email.
        /// </summary>
        internal static string EmailIncorrect {
            get {
                return ResourceManager.GetString("EmailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obiekt jest pusty.
        /// </summary>
        internal static string IsNull {
            get {
                return ResourceManager.GetString("IsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateEnd nie może być mniejsza od DateStart.
        /// </summary>
        internal static string MatchIncorectDateEnd {
            get {
                return ResourceManager.GetString("MatchIncorectDateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchId jest równe 0.
        /// </summary>
        internal static string MatchNoId {
            get {
                return ResourceManager.GetString("MatchNoId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameData nie jest w formacie JSON.
        /// </summary>
        internal static string MatchNoJsonFormatGameData {
            get {
                return ResourceManager.GetString("MatchNoJsonFormatGameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie ma użytkownika o ID: {0}.
        /// </summary>
        internal static string MatchNoUser {
            get {
                return ResourceManager.GetString("MatchNoUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MatchUsers jest puste.
        /// </summary>
        internal static string MatchNoUsers {
            get {
                return ResourceManager.GetString("MatchNoUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateStart ma pustą wartość.
        /// </summary>
        internal static string MatchNullDateStart {
            get {
                return ResourceManager.GetString("MatchNullDateStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest puste.
        /// </summary>
        internal static string NoPassword {
            get {
                return ResourceManager.GetString("NoPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie znaleziono użytkownika.
        /// </summary>
        internal static string NullUser {
            get {
                return ResourceManager.GetString("NullUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowe hasło jest takie samo jak stare.
        /// </summary>
        internal static string PasswordChangeThisSame {
            get {
                return ResourceManager.GetString("PasswordChangeThisSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło zawiera białe znaki.
        /// </summary>
        internal static string PasswordHaveWhiteSpace {
            get {
                return ResourceManager.GetString("PasswordHaveWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło nie zawiera liczb.
        /// </summary>
        internal static string PasswordNoDigit {
            get {
                return ResourceManager.GetString("PasswordNoDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło nie zawiera specjalnych symboli.
        /// </summary>
        internal static string PasswordNoSpecialSymbol {
            get {
                return ResourceManager.GetString("PasswordNoSpecialSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nie poprawne hasło.
        /// </summary>
        internal static string PasswordNotCompare {
            get {
                return ResourceManager.GetString("PasswordNotCompare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło nie zawiera dużych liter.
        /// </summary>
        internal static string PasswordNoUpperSymbol {
            get {
                return ResourceManager.GetString("PasswordNoUpperSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powtórzone hasło nie zgadza z wpisanym hasłem.
        /// </summary>
        internal static string PasswordRepeatNotThisSame {
            get {
                return ResourceManager.GetString("PasswordRepeatNotThisSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest za długie.
        /// </summary>
        internal static string PasswordTooLong {
            get {
                return ResourceManager.GetString("PasswordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasło jest za krótkie.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pusta nazwa użytownika.
        /// </summary>
        internal static string UserEmptyName {
            get {
                return ResourceManager.GetString("UserEmptyName", resourceCulture);
            }
        }
    }
}
